"use client";

import React, { useState, useEffect, useMemo, useCallback } from "react";
import { useLocale } from "@/contexts/LocaleContext";
import {
  Compass,
  MapPin,
  Plus,
  Search,
  Heart,
  MessageCircle as CommentIcon,
  Share2,
  Eye,
  ChevronDown,
  ChevronUp,
  Star,
  Briefcase,
  Phone,
  Circle,
  ScanLine,
  Bot,
  Coins,
  ExternalLink,
  Tag,
  Navigation,
  Building2,
  Sparkles,
  Code,
  Clipboard,
} from "lucide-react";
import { SkeletonFeed } from "@/components/ui/Skeleton";
import { analyzeLocalSignals } from "@/lib/explore/local-signals";
import { getCurrentPosition, haversineMeters, HAIFA_CENTER } from "@/lib/explore/geolocation";
import { getExploreModules } from "@/lib/explore/modules";
import { useArchitect } from "@/contexts/ArchitectContext";
import { PanelWrapper } from "@/components/dashboard/PanelWrapper";

const TEAL = "#008080";
const MY_LOCATION_LABEL = "My Location"; // Simulated; in production from geolocation

function formatDistance(meters: number): string {
  if (meters < 1000) return `${meters}m`;
  return `${(meters / 1000).toFixed(1).replace(/\.0$/, "")}km`;
}

type ExploreTab = "all" | "deals" | "gossip" | "jobs" | "pros";

const RADII_OPTIONS = [1, 3, 5, 10, 25, 50];

// --- Post & comment types ---
export type PostCategory = "deals" | "gossip" | "jobs" | "pros";

export interface PostComment {
  id: string;
  authorName: string;
  authorAvatar?: string;
  text: string;
  timestamp: string;
  replies?: PostComment[];
}

export interface ExplorePost {
  id: string;
  category: PostCategory;
  authorName: string;
  authorAvatar?: string;
  timestamp: string; // e.g. "2 hours ago"
  title: string;
  description: string;
  likes: number;
  comments: number;
  shares: number;
  views: number;
  commentsList: PostComment[];
  // Category-specific
  location?: string;
  price?: string;
  discountPercent?: number;
  hashtags?: string[];
  trending?: boolean;
  salaryRange?: string;
  workMode?: "Remote" | "Hybrid" | "On-site";
  rating?: number;
  specialty?: string;
  /** When true, show "Generated by Ollin AI" badge and AI-style copy/CTA */
  generatedByAI?: boolean;
  /** AI-aggregated one-liner (e.g. "Multiple reports of filming near you", "[Brand] is offering 30% off today") */
  aiSummary?: string;
  /** Professional source label for AI posts (e.g. "Sourced from: WhatsApp Groups") */
  sourceLabel?: string;
  /** Job posts: link to original listing (LinkedIn/Indeed) — simulated URL */
  sourceLink?: string;
  /** Job posts: human-readable source name (e.g. "LinkedIn", "Indeed") */
  sourceName?: string;
  /** Optional image URL (copyright-safe: use placeholder when absent) */
  imageUrl?: string;
  /** Exact distance in meters for proximity badge (e.g. 100, 500, 3000) */
  distanceMeters?: number;
  /** Full address for display and navigation */
  address?: string;
  /** Status pill: Hot Deal, Urgent Hiring, Trending Now */
  statusPill?: "Hot Deal" | "Urgent Hiring" | "Trending Now";
  /** Coordinates for distance calculation (from geolocation/geocode) */
  lat?: number;
  lng?: number;
}

// --- Sample posts (3-4 per category) ---
const SAMPLE_POSTS: ExplorePost[] = [
  // DEALS
  {
    id: "d1",
    category: "deals",
    authorName: "Sarah M.",
    timestamp: "2 hours ago",
    title: "50% off at the new café on Main Street",
    description: "Grand opening week — half off all pastries and coffee. Perfect spot for remote work. Valid until Sunday.",
    likes: 24,
    comments: 5,
    shares: 3,
    views: 312,
    location: "Tel Aviv",
    address: "Main St 42, Tel Aviv",
    distanceMeters: 100,
    lat: 32.0853,
    lng: 34.7818,
    statusPill: "Hot Deal",
    price: "From ₪15",
    discountPercent: 50,
    generatedByAI: true,
    aiSummary: "Local cafés are offering 50% off today in your area.",
    sourceLabel: "Sourced from: WhatsApp Groups, Local Business Pages",
    sourceLink: "https://example.com/deals/cafe-main-street",
    sourceName: "Local Business",
    commentsList: [
      { id: "c1", authorName: "David L.", text: "Worth the queue!", timestamp: "1h ago", replies: [{ id: "r1", authorName: "Sarah M.", text: "Queue moves fast 😊", timestamp: "45m ago" }, { id: "r2", authorName: "Mike R.", text: "Agreed, great deal.", timestamp: "30m ago" }] },
      { id: "c2", authorName: "Noa K.", text: "Do they have oat milk?", timestamp: "30m ago" },
    ],
  },
  {
    id: "d2",
    category: "deals",
    authorName: "Deals Hunter",
    timestamp: "5 hours ago",
    title: "Gym membership flash sale — 3 months for price of 1",
    description: "Local fitness center is running a limited offer. Great way to start the year. DM for the code.",
    likes: 41,
    comments: 8,
    shares: 12,
    views: 589,
    location: "Haifa",
    address: "HaAtzmaut St 88, Haifa",
    distanceMeters: 500,
    lat: 32.794,
    lng: 34.9896,
    statusPill: "Hot Deal",
    price: "₪199",
    discountPercent: 66,
    generatedByAI: true,
    aiSummary: "Gym chains are offering 3-for-1 membership deals this week.",
    sourceLabel: "Source: Facebook Marketplace, Partner Gym RSS",
    sourceLink: "https://example.com/deals/gym-flash",
    sourceName: "Facebook Marketplace",
    commentsList: [{ id: "c3", authorName: "Alex T.", text: "Just signed up, thanks!", timestamp: "2h ago" }],
  },
  {
    id: "d3",
    category: "deals",
    authorName: "Local Deals",
    timestamp: "1 day ago",
    title: "Free delivery on orders over ₪100 — grocery app",
    description: "Use code LOCAL24 at checkout. Works for all supermarkets on the app. Min order ₪100.",
    likes: 67,
    comments: 14,
    shares: 22,
    views: 1204,
    location: "Jerusalem",
    address: "Jaffa Rd 100, Jerusalem",
    distanceMeters: 3000,
    lat: 31.7683,
    lng: 35.2137,
    price: "Free",
    discountPercent: 0,
    generatedByAI: true,
    sourceLabel: "Source: Grocery App API, Tel Aviv Municipality RSS",
    sourceLink: "https://example.com/deals/grocery-delivery",
    sourceName: "Grocery App",
    commentsList: [],
  },
  {
    id: "d4",
    category: "deals",
    authorName: "Roni B.",
    timestamp: "3 hours ago",
    title: "Second-hand kids gear pop-up this weekend",
    description: "Strollers, cribs, toys in great condition. Cash only. Saturday 9–14 at the community center.",
    likes: 18,
    comments: 4,
    shares: 2,
    views: 156,
    location: "Ramat Gan",
    address: "Bialik St 15, Ramat Gan",
    distanceMeters: 800,
    statusPill: "Hot Deal",
    price: "Various",
    discountPercent: 40,
    commentsList: [],
  },
  // GOSSIP
  {
    id: "g1",
    category: "gossip",
    authorName: "Neighbor Watch",
    timestamp: "1 hour ago",
    title: "BREAKING: New Restaurant on Main Draws Crowds — 45 Min Wait",
    description: "Finally tried it last night. Local buzz confirms the new corner spot is packed. Pasta praised; get there early or book ahead. What’s your take?",
    likes: 89,
    comments: 32,
    shares: 7,
    views: 892,
    hashtags: ["food", "local", "restaurant"],
    trending: true,
    statusPill: "Trending Now",
    location: "Tel Aviv",
    address: "Rothschild Blvd 52, Tel Aviv",
    generatedByAI: true,
    aiSummary: "Multiple reports: new restaurant drawing long queues. Pasta and atmosphere praised.",
    sourceLabel: "Sourced from: WhatsApp Groups, Neighborhood Forums",
    commentsList: [
      { id: "g1c1", authorName: "Foodie_J", text: "Worth every minute!", timestamp: "45m ago", replies: [{ id: "g1r1", authorName: "Neighbor Watch", text: "Same here 🍝", timestamp: "30m ago" }] },
    ],
  },
  {
    id: "g2",
    category: "gossip",
    authorName: "City Talk",
    timestamp: "4 hours ago",
    title: "BREAKING: Major Filming Shuts Down Rothschild — Production Trucks Everywhere",
    description: "Large-scale shoot reported along Rothschild. Traffic rerouted. Show or film TBA.",
    likes: 156,
    comments: 44,
    shares: 28,
    views: 2103,
    hashtags: ["filming", "Rothschild", "TV"],
    trending: true,
    statusPill: "Trending Now",
    location: "Tel Aviv",
    address: "Rothschild Blvd 80–120, Tel Aviv",
    generatedByAI: true,
    aiSummary: "Multiple reports of filming and production activity on Rothschild today.",
    sourceLabel: "Source: Tel Aviv Municipality RSS, Local Twitter",
    commentsList: [],
  },
  {
    id: "g3",
    category: "gossip",
    authorName: "Local Mom",
    timestamp: "6 hours ago",
    title: "LOCAL ROUNDUP: Top Pediatricians in the Area — English-Speaking Options",
    description: "Roundup of recommended pediatricians for families. Patient, English-friendly practices highlighted.",
    likes: 34,
    comments: 19,
    shares: 2,
    views: 445,
    hashtags: ["parents", "recommendations", "health"],
    generatedByAI: true,
    sourceLabel: "Sourced from: WhatsApp Groups, Parent Communities",
    commentsList: [],
  },
  {
    id: "g4",
    category: "gossip",
    authorName: "Tech Guy",
    timestamp: "12 hours ago",
    title: "ISP COMPARISON: Bezeq vs Partner vs Cellcom — Speeds & Prices in Your Building",
    description: "Community-reported speeds and prices: comparison table for Bezeq, Partner, and Cellcom in your area.",
    likes: 72,
    comments: 41,
    shares: 15,
    views: 678,
    hashtags: ["internet", "comparison", "tech"],
    commentsList: [],
  },
  // JOBS
  {
    id: "j1",
    category: "jobs",
    authorName: "Startup Alpha",
    timestamp: "3 hours ago",
    title: "Senior Frontend Developer (React/TypeScript)",
    description: "We’re a small product team building B2B SaaS. You’ll own the web app end-to-end. 3+ years experience.",
    likes: 28,
    comments: 6,
    shares: 4,
    views: 234,
    salaryRange: "₪25k–35k",
    workMode: "Hybrid",
    location: "Tel Aviv",
    address: "Rothschild Blvd 22, Tel Aviv",
    distanceMeters: 200,
    statusPill: "Urgent Hiring",
    generatedByAI: true,
    sourceLabel: "Source: LinkedIn Jobs, Startup Alpha Careers",
    sourceLink: "https://www.linkedin.com/jobs/view/123456789",
    sourceName: "LinkedIn",
    commentsList: [],
  },
  {
    id: "j2",
    category: "jobs",
    authorName: "Design Studio",
    timestamp: "1 day ago",
    title: "UX/UI Designer — full-time",
    description: "Brand and digital product design. Figma, user research, and client work. Portfolio required.",
    likes: 45,
    comments: 12,
    shares: 8,
    views: 567,
    salaryRange: "₪18k–24k",
    workMode: "Remote",
    location: "Tel Aviv",
    address: "Dizengoff St 100, Tel Aviv",
    distanceMeters: 500,
    statusPill: "Urgent Hiring",
    generatedByAI: true,
    sourceLabel: "Source: LinkedIn, Design Studio Jobs",
    sourceLink: "https://www.linkedin.com/jobs/view/987654321",
    sourceName: "LinkedIn",
    commentsList: [],
  },
  {
    id: "j3",
    category: "jobs",
    authorName: "Local Restaurant",
    timestamp: "5 hours ago",
    title: "Part-time waitstaff and barista",
    description: "Weekends and some evenings. Friendly team, tips. No experience needed — we train.",
    likes: 19,
    comments: 3,
    shares: 1,
    views: 198,
    salaryRange: "By hour + tips",
    workMode: "On-site",
    location: "Haifa",
    address: "HaNevi'im St 45, Haifa",
    distanceMeters: 350,
    statusPill: "Urgent Hiring",
    generatedByAI: true,
    sourceLabel: "Sourced from: WhatsApp Groups, Local Restaurant",
    sourceLink: "https://www.indeed.com/viewjob?jk=abc123",
    sourceName: "Indeed",
    commentsList: [],
  },
  {
    id: "j4",
    category: "jobs",
    authorName: "Tech Corp",
    timestamp: "2 days ago",
    title: "DevOps / SRE Engineer",
    description: "Kubernetes, AWS, CI/CD. On-call rotation. Great benefits and growth.",
    likes: 62,
    comments: 9,
    shares: 11,
    views: 712,
    salaryRange: "₪30k–42k",
    workMode: "Remote",
    location: "Tel Aviv",
    address: "Azrieli Center, Tel Aviv",
    distanceMeters: 1200,
    statusPill: "Urgent Hiring",
    generatedByAI: true,
    sourceLabel: "Source: LinkedIn, Tech Corp Careers",
    sourceLink: "https://www.linkedin.com/jobs/view/555555555",
    sourceName: "LinkedIn",
    commentsList: [],
  },
  // PROS
  {
    id: "p1",
    category: "pros",
    authorName: "Dan Electric",
    timestamp: "4 hours ago",
    title: "Licensed electrician — home & office",
    description: "Wiring, panels, smart home, repairs. Same-day service in Gush Dan. 15 years experience.",
    likes: 38,
    comments: 5,
    shares: 2,
    views: 289,
    rating: 4.9,
    specialty: "Electrician",
    location: "Tel Aviv",
    address: "Ibn Gvirol 55, Tel Aviv",
    distanceMeters: 400,
    generatedByAI: true,
    sourceLabel: "Sourced from: Ollin Pro Network, Google Business",
    commentsList: [],
  },
  {
    id: "p2",
    category: "pros",
    authorName: "Levy & Co. Law",
    timestamp: "1 day ago",
    title: "Contract and business law — free first consultation",
    description: "Startups, freelancers, small business. We keep it simple and transparent.",
    likes: 22,
    comments: 4,
    shares: 1,
    views: 156,
    rating: 4.8,
    specialty: "Lawyer",
    location: "Tel Aviv",
    generatedByAI: true,
    sourceLabel: "Source: Tel Aviv Bar Association, Legal Directories",
    commentsList: [],
  },
  {
    id: "p3",
    category: "pros",
    authorName: "Green Thumb Gardening",
    timestamp: "6 hours ago",
    title: "Garden design and maintenance",
    description: "Design, planting, irrigation, pruning. Residential and small commercial. Eco-friendly options.",
    likes: 31,
    comments: 7,
    shares: 3,
    views: 201,
    rating: 4.7,
    specialty: "Gardener",
    location: "Ramat Gan",
    address: "Bialik 8, Ramat Gan",
    distanceMeters: 900,
    commentsList: [],
  },
  {
    id: "p4",
    category: "pros",
    authorName: "Plumber Ron",
    timestamp: "8 hours ago",
    title: "24/7 plumbing — no extra charge for nights",
    description: "Leaks, blockages, boilers, renovations. Licensed and insured. Serving Tel Aviv and center.",
    likes: 44,
    comments: 11,
    shares: 6,
    views: 334,
    rating: 4.9,
    specialty: "Plumber",
    location: "Tel Aviv",
    address: "Allenby 30, Tel Aviv",
    distanceMeters: 250,
    generatedByAI: true,
    sourceLabel: "Sourced from: Ollin Pro Network, Local Reviews",
    commentsList: [],
  },
];

function getInitial(name: string): string {
  return (name || "?").replace(/\s+.*$/, "").slice(0, 1).toUpperCase();
}

/** Copyright-safe image placeholder by category: brand (deals/jobs), news (gossip), pro */
function PostImagePlaceholder({
  category,
  trending,
  imageUrl,
  className = "",
}: {
  category: PostCategory;
  trending?: boolean;
  imageUrl?: string;
  className?: string;
}) {
  const isNews = category === "gossip";
  const isLarge = isNews && trending;
  const base = "flex items-center justify-center bg-gray-100 text-gray-400 overflow-hidden " + className;
  if (imageUrl) {
    return (
      <div className={base + " bg-gray-200"}>
        <img src={imageUrl} alt="" className="w-full h-full object-cover" />
      </div>
    );
  }
  if (category === "deals" || category === "jobs") {
    return (
      <div className={base + " bg-gradient-to-br from-[#008080]/10 to-gray-100"}>
        <Tag className="w-8 h-8 text-[#008080]/50" strokeWidth={1.5} />
      </div>
    );
  }
  if (category === "gossip") {
    return (
      <div className={base + " bg-gradient-to-br from-amber-100/80 to-gray-200 backdrop-blur-sm"}>
        <MapPin className="w-8 h-8 text-amber-600/60" strokeWidth={1.5} />
      </div>
    );
  }
  return (
    <div className={base + " bg-gradient-to-br from-[#008080]/10 to-gray-100"}>
      <Star className="w-8 h-8 text-[#008080]/50" strokeWidth={1.5} />
    </div>
  );
}

/** Always return a string safe for React (no objects). Accepts string, number, or Date from API. */
function formatRelative(t: string | number | Date | null | undefined): string {
  if (t == null) return "";
  if (typeof t === "string") return t;
  if (typeof t === "number") return String(t);
  if (typeof t === "object" && "toISOString" in t) return (t as Date).toISOString();
  return String(t);
}

/** Modal: show route from My Location to destination; Open in Maps link */
function DirectionsModal({
  destinationAddress,
  destinationTitle,
  onClose,
  isHe,
}: {
  destinationAddress: string;
  destinationTitle?: string;
  onClose: () => void;
  isHe: boolean;
}) {
  const mapsUrl =
    "https://www.google.com/maps/dir/?api=1&destination=" + encodeURIComponent(destinationAddress);

  const openMaps = () => {
    window.open(mapsUrl, "_blank", "noopener,noreferrer");
    onClose();
  };

  return (
    <>
      <div className="fixed inset-0 z-50 bg-black/50" onClick={onClose} aria-hidden />
      <div className="fixed left-1/2 top-1/2 z-50 w-full max-w-sm -translate-x-1/2 -translate-y-1/2 rounded-xl bg-white p-4 shadow-xl" onClick={(e) => e.stopPropagation()}>
        <div className="flex items-center gap-2 text-[#008080] mb-2">
          <Navigation className="w-5 h-5" strokeWidth={2} />
          <h3 className="font-semibold text-gray-900">{isHe ? "הגעה" : "Get Directions"}</h3>
        </div>
        <p className="text-xs text-gray-500 mb-1">{isHe ? "מ-" : "From"}: {MY_LOCATION_LABEL}</p>
        <p className="text-xs text-gray-500 mb-1">{isHe ? "אל" : "To"}: {destinationTitle || destinationAddress}</p>
        <p className="text-sm text-gray-800 mb-4 break-words">{destinationAddress}</p>
        <div className="flex gap-2">
          <button type="button" onClick={onClose} className="flex-1 py-2.5 rounded-xl border border-gray-200 text-sm font-medium text-gray-700 hover:bg-gray-50">
            {isHe ? "ביטול" : "Cancel"}
          </button>
          <button type="button" onClick={openMaps} className="flex-1 py-2.5 rounded-xl text-white text-sm font-medium bg-[#008080] hover:bg-[#006666] flex items-center justify-center gap-2">
            <MapPin className="w-4 h-4" strokeWidth={2} />
            {isHe ? "פתח במפות" : "Open in Maps"}
          </button>
        </div>
      </div>
    </>
  );
}

// --- AI Insight templates (injected every 30s); Haifa/Tel Aviv local summaries
const INSIGHT_TEMPLATES: Omit<ExplorePost, "id" | "timestamp" | "commentsList">[] = [
  {
    category: "gossip",
    authorName: "Ollin AI",
    title: "Summary of 5 local messages",
    description: "Water outage reported in Herzl St. Expected back by 18:00. Traffic delay on Dizengoff due to works.",
    likes: 0,
    comments: 0,
    shares: 0,
    views: 0,
    location: "Tel Aviv",
    hashtags: ["local", "alerts"],
    trending: true,
    generatedByAI: true,
    aiSummary: "Summary of 5 local messages: Water outage reported in Herzl St.",
    sourceLabel: "Sourced from: WhatsApp Groups, Tel Aviv Municipality RSS",
    statusPill: "Trending Now",
  },
  {
    category: "deals",
    authorName: "Ollin AI",
    title: "Web scan result",
    description: "30% discount found at Greg Cafe nearby. Valid today. Show this message at checkout.",
    likes: 0,
    comments: 0,
    shares: 0,
    views: 0,
    location: "Tel Aviv",
    price: "30% off",
    discountPercent: 30,
    generatedByAI: true,
    aiSummary: "Web scan result: 30% discount found at 'Greg Cafe' nearby.",
    sourceLabel: "Source: Web crawl, Greg Cafe website, Local deal aggregators",
    address: "Dizengoff St 100, Tel Aviv-Yafo",
    distanceMeters: 350,
    lat: 32.0778,
    lng: 34.7758,
    statusPill: "Hot Deal",
  },
  {
    category: "jobs",
    authorName: "Ollin AI",
    title: "New listing from LinkedIn",
    description: "Senior Designer needed — 2.5 km away. Hybrid. Apply via Ollin Quick Apply.",
    likes: 0,
    comments: 0,
    shares: 0,
    views: 0,
    location: "Tel Aviv",
    salaryRange: "Competitive",
    workMode: "Hybrid",
    generatedByAI: true,
    aiSummary: "New listing from LinkedIn: Senior Designer needed (2.5 km away).",
    sourceLabel: "Source: LinkedIn Jobs, Company careers page",
    sourceLink: "https://www.linkedin.com/jobs/view/insight-senior-designer",
    sourceName: "LinkedIn",
    address: "Rothschild Blvd 22, Tel Aviv-Yafo",
    distanceMeters: 2500,
    lat: 32.0645,
    lng: 34.7742,
    statusPill: "Urgent Hiring",
  },
  {
    category: "pros",
    authorName: "Ollin AI",
    title: "Pro active in your radius",
    description: "Dan Electric — 4.9★, 1.2 km away. Licensed electrician, same-day service in Gush Dan.",
    likes: 0,
    comments: 0,
    shares: 0,
    views: 0,
    location: "Tel Aviv",
    rating: 4.9,
    specialty: "Electrician",
    generatedByAI: true,
    aiSummary: "Pro active in your radius: Dan Electric (4.9★, 1.2 km away).",
    sourceLabel: "Sourced from: Ollin Pro Network, Google Business",
    address: "Arlozorov St 45, Tel Aviv-Yafo",
    distanceMeters: 1200,
    lat: 32.0875,
    lng: 34.7812,
  },
  {
    category: "gossip",
    authorName: "Ollin AI",
    title: "Haifa local summary",
    description: "Multiple reports of roadworks on Moriah Ave. New vegan spot opening on Hanassi Blvd this week.",
    likes: 0,
    comments: 0,
    shares: 0,
    views: 0,
    location: "Haifa",
    hashtags: ["haifa", "traffic", "food"],
    generatedByAI: true,
    aiSummary: "Summary of local messages: Roadworks on Moriah Ave; new vegan spot on Hanassi Blvd.",
    sourceLabel: "Sourced from: WhatsApp Groups, Haifa Municipality RSS",
  },
  {
    category: "deals",
    authorName: "Ollin AI",
    title: "Deal nearby (Haifa)",
    description: "20% off at Cafe Neto in Hadar. Weekend brunch offer.",
    likes: 0,
    comments: 0,
    shares: 0,
    views: 0,
    location: "Haifa",
    price: "20% off",
    discountPercent: 20,
    generatedByAI: true,
    aiSummary: "Web scan result: 20% discount at Cafe Neto (Haifa) nearby.",
    sourceLabel: "Source: Facebook Marketplace, Local business pages",
  },
];

// --- Post card: proximity badge, Get Directions, address, glassmorphism, status pills ---
function PostCard({
  post,
  isHe,
  onLike,
  liked,
  onSourceClick,
  onGetDirections,
  onApplyClick,
}: {
  post: ExplorePost;
  isHe: boolean;
  onLike: (id: string) => void;
  liked: Set<string>;
  onSourceClick?: (post: ExplorePost) => void;
  onGetDirections?: (address: string, title?: string) => void;
  onApplyClick?: (post: ExplorePost) => void;
}) {
  const [showReplies, setShowReplies] = useState<Record<string, boolean>>({});
  const [addressExpanded, setAddressExpanded] = useState(false);
  const [justCopied, setJustCopied] = useState(false);
  const toggleReplies = (commentId: string) => {
    setShowReplies((prev) => ({ ...prev, [commentId]: !prev[commentId] }));
  };

  const isTrendingGossip = post.category === "gossip" && post.trending;
  const sourceHref = post.sourceLink || (post.generatedByAI ? "#" : undefined);
  const sourceDisplayName = post.sourceName || (post.sourceLabel?.replace(/^Sourced from:?\s*/i, "").split(",")[0]?.trim()) || "Original";
  const hasProximity = (post.category === "deals" || post.category === "jobs" || post.category === "pros") && post.distanceMeters != null;
  const distanceDisplay = hasProximity ? formatDistance(post.distanceMeters!) : null;

  const handleSourceClick = () => {
    if ((post.category === "deals" || post.category === "jobs") && post.generatedByAI && onSourceClick) {
      onSourceClick(post);
    }
  };

  const handleCopy = useCallback(() => {
    const title = post.category === "gossip" && post.generatedByAI ? (post.aiSummary || post.title) : post.title;
    const summary = post.aiSummary || post.description;
    const text = [title, summary].filter(Boolean).join("\n\n");
    navigator.clipboard.writeText(text).then(() => {
      setJustCopied(true);
      setTimeout(() => setJustCopied(false), 1000);
    });
  }, [post]);

  return (
    <article className="rounded-xl border border-gray-200 bg-white overflow-hidden shadow-md hover:shadow-lg transition-shadow cursor-pointer lg:rounded-2xl">
      {/* Large image block with glassmorphism overlay — social-style larger images */}
      <div className="relative">
        {isTrendingGossip ? (
          <PostImagePlaceholder category="gossip" trending imageUrl={post.imageUrl} className="w-full h-52 sm:h-56 lg:h-60 rounded-t-xl lg:rounded-t-2xl" />
        ) : (
          <PostImagePlaceholder category={post.category} imageUrl={post.imageUrl} className="w-full h-44 sm:h-48 lg:h-52 rounded-t-xl lg:rounded-t-2xl" />
        )}
        {/* Glassmorphism overlay: bold headline or status */}
        <div className="absolute inset-0 rounded-t-xl bg-gradient-to-t from-black/60 via-transparent to-transparent pointer-events-none" />
        <div className="absolute bottom-0 left-0 right-0 p-3 pointer-events-none">
          <div className="backdrop-blur-md bg-white/20 rounded-lg px-2.5 py-1.5 border border-white/30">
            <span className="text-sm font-bold text-white drop-shadow-md line-clamp-2">
              {post.category === "gossip" ? (post.aiSummary || post.title) : post.title}
            </span>
          </div>
        </div>
        {/* Prominent distance badge (teal) — top-right: "100m from you" */}
        {distanceDisplay && (
          <div className="absolute top-2 right-2 rounded-lg bg-[#008080] text-white px-2.5 py-1.5 text-sm font-bold shadow-lg whitespace-nowrap">
            {distanceDisplay} {isHe ? "ממך" : "from you"}
          </div>
        )}
        {/* Status pill — top-left */}
        {post.statusPill && (
          <div className="absolute top-2 left-2 rounded-lg px-2.5 py-1 text-xs font-bold uppercase tracking-wide shadow-lg bg-white/90 text-gray-900 border border-white/50">
            {post.statusPill === "Hot Deal" && (isHe ? "דיל חם" : "Hot Deal")}
            {post.statusPill === "Urgent Hiring" && (isHe ? "מגייסים עכשיו" : "Urgent Hiring")}
            {post.statusPill === "Trending Now" && (isHe ? "טרנדי עכשיו" : "Trending Now")}
          </div>
        )}
      </div>

      <div className="flex">
        {!isTrendingGossip && (
          <PostImagePlaceholder category={post.category} imageUrl={post.imageUrl} className="w-28 h-28 sm:w-32 sm:h-32 lg:w-36 lg:h-36 flex-shrink-0 rounded-l-xl lg:rounded-l-2xl" />
        )}
        <div className="flex-1 min-w-0">
          {/* Header: Avatar, Name, Timestamp + AI badge — desktop: slightly larger */}
          <div className="flex items-center gap-3 px-3 py-2.5 lg:px-4 lg:py-3 border-b border-gray-100">
            <div className="w-8 h-8 rounded-full bg-[#008080]/15 flex items-center justify-center text-xs font-semibold text-[#008080] shrink-0">
              {post.authorAvatar ? <img src={post.authorAvatar} alt="" className="w-full h-full rounded-full object-cover" /> : getInitial(post.authorName)}
            </div>
            <div className="flex-1 min-w-0">
              <p className="font-medium text-gray-900 text-xs truncate">{post.authorName}</p>
              <p className="text-[10px] text-gray-500">{formatRelative(post.timestamp)}</p>
            </div>
            {post.generatedByAI && (
              <span className="flex items-center gap-1 px-1.5 py-0.5 rounded-lg bg-[#008080]/10 text-[#008080] text-[9px] font-medium shrink-0">
                <Bot className="w-2.5 h-2.5" strokeWidth={2} />
                AI
              </span>
            )}
          </div>

          {/* Content: bold headers + clear source attribution — selectable text for copy/long-press */}
          <div className="px-3 py-2 lg:px-4 lg:py-3 select-text">
            <h3 className={`mb-1 ${post.category === "gossip" || post.category === "deals" ? "text-sm font-bold text-gray-900 uppercase tracking-tight leading-tight" : "font-bold text-gray-900 text-sm"}`}>
              {post.category === "gossip" && post.generatedByAI ? (post.aiSummary || post.title) : post.title}
            </h3>
            {post.generatedByAI && post.sourceLabel && (
              <p className="text-[10px] text-gray-500 font-medium mb-1">{post.sourceLabel}</p>
            )}
            {post.category === "gossip" && post.generatedByAI && post.aiSummary && post.title !== post.aiSummary && (
              <p className="text-xs text-amber-800/90 italic leading-snug mb-1">{post.title}</p>
            )}
            {post.category !== "gossip" && post.generatedByAI && post.aiSummary && (
              <p className="text-xs text-[#008080]/90 italic leading-snug mb-1">{post.aiSummary}</p>
            )}
            <p className="text-xs text-gray-600 leading-snug line-clamp-3">{post.description}</p>
          </div>

          {/* Address + live distance (high-contrast teal "Xm from you") + Get Directions */}
          {(post.address || hasProximity) && (post.category === "deals" || post.category === "jobs" || post.category === "pros") && (
            <div className="px-3 pb-2">
              <div className="flex items-center gap-2 rounded-lg bg-gray-50 border border-gray-100 p-2">
                {post.address ? (
                  <button
                    type="button"
                    onClick={() => onGetDirections?.(post.address!, post.title)}
                    className="flex-1 min-w-0 text-left flex items-center gap-2 group"
                  >
                    <MapPin className="w-4 h-4 text-[#008080] shrink-0" strokeWidth={2} />
                    <span className={`text-xs text-gray-700 ${addressExpanded ? "" : "truncate"}`} title={post.address}>
                      {post.address}
                    </span>
                    {distanceDisplay && (
                      <span className="shrink-0 text-xs font-bold text-[#008080]" title={isHe ? "מרחק ממך" : "Distance from you"}>
                        {distanceDisplay} {isHe ? "ממך" : "from you"}
                      </span>
                    )}
                    {post.address.length > 40 && (
                      <button type="button" className="text-[10px] text-[#008080] shrink-0 font-medium" onClick={(e) => { e.stopPropagation(); setAddressExpanded((a) => !a); }}>
                        {addressExpanded ? (isHe ? "פחות" : "Less") : (isHe ? "הרחב" : "Expand")}
                      </button>
                    )}
                  </button>
                ) : (
                  <span className="text-xs text-gray-500 flex-1">{distanceDisplay && <span className="font-bold text-[#008080]">{distanceDisplay} {isHe ? "ממך" : "from you"}</span>}</span>
                )}
                <button
                  type="button"
                  onClick={() => onGetDirections?.(post.address || "", post.title)}
                  disabled={!post.address}
                  className="shrink-0 p-2 rounded-lg bg-[#008080] text-white hover:bg-[#006666] disabled:opacity-50 disabled:cursor-not-allowed"
                  title={isHe ? "הגעה" : "Get Directions"}
                >
                  <Navigation className="w-4 h-4" strokeWidth={2} />
                </button>
              </div>
            </div>
          )}

          {/* Jobs: company logo + Ollin Apply CTA */}
          {post.category === "jobs" && (
            <div className="px-3 pb-2 flex items-center gap-3">
              <div className="w-10 h-10 rounded-lg bg-[#008080]/10 flex items-center justify-center text-[#008080] shrink-0">
                <Building2 className="w-5 h-5" strokeWidth={2} />
              </div>
              <button
                type="button"
                onClick={() => onApplyClick?.(post)}
                className="flex-1 py-2.5 rounded-xl bg-[#008080] text-white text-sm font-bold hover:bg-[#006666] flex items-center justify-center gap-2"
              >
                {isHe ? "הגש מועמדות באולין" : "Ollin Apply"}
                {distanceDisplay && <span className="opacity-90 text-xs font-medium">— {distanceDisplay} {isHe ? "מכאן" : "from here"}</span>}
              </button>
            </div>
          )}

          {/* Category-specific badges */}
          <div className="px-3 pb-2 flex flex-wrap gap-1.5">
        {post.category === "deals" && (
          <>
            <span className="inline-flex items-center gap-1 px-2.5 py-1 rounded-lg bg-amber-100 text-amber-800 text-xs font-medium">
              <Coins className="w-3 h-3" strokeWidth={2} />
              {isHe ? "הרווח קרדיטים ברכישה" : "Earn Credits on Purchase"}
            </span>
            {(post.discountPercent ?? 0) > 0 && (
              <span className="inline-flex items-center px-2.5 py-1 rounded-lg bg-red-100 text-red-700 text-xs font-medium">
                -{post.discountPercent}%
              </span>
            )}
            {post.price && (
              <span className="inline-flex items-center px-2.5 py-1 rounded-lg bg-[#008080]/10 text-[#008080] text-xs font-medium">
                {post.price}
              </span>
            )}
            {post.location && (
              <span className="inline-flex items-center gap-1 px-2.5 py-1 rounded-lg bg-gray-100 text-gray-700 text-xs">
                <MapPin className="w-3 h-3" strokeWidth={2} />
                {post.location}
              </span>
            )}
          </>
        )}
        {post.category === "gossip" && (
          <>
            <span className="inline-flex items-center px-2.5 py-1 rounded-lg bg-amber-200 text-amber-900 text-[10px] font-bold uppercase tracking-wide">
              {isHe ? "צהובון" : "Yellow Press"}
            </span>
            {post.trending && (
              <span className="inline-flex items-center px-2.5 py-1 rounded-lg bg-amber-100 text-amber-800 text-xs font-medium">
                Trending
              </span>
            )}
            {post.hashtags?.map((tag) => (
              <span key={tag} className="text-xs text-[#008080] font-medium">#{tag}</span>
            ))}
          </>
        )}
        {post.category === "jobs" && (
          <>
            {post.salaryRange && (
              <span className="inline-flex items-center px-2.5 py-1 rounded-lg bg-[#008080]/10 text-[#008080] text-xs font-medium">
                {post.salaryRange}
              </span>
            )}
            {post.workMode && (
              <span className="inline-flex items-center gap-1 px-2.5 py-1 rounded-lg bg-gray-100 text-gray-700 text-xs">
                <Briefcase className="w-3 h-3" strokeWidth={2} />
                {post.workMode}
              </span>
            )}
          </>
        )}
        {post.category === "pros" && (
          <>
            {post.rating != null && (
              <span className="inline-flex items-center gap-1 px-2.5 py-1 rounded-lg bg-amber-100 text-amber-800 text-xs font-medium">
                <Star className="w-3 h-3 fill-amber-500 text-amber-500" strokeWidth={2} />
                {post.rating}
              </span>
            )}
            {post.specialty && (
              <span className="inline-flex items-center px-2.5 py-1 rounded-lg bg-gray-100 text-gray-700 text-xs">
                {post.specialty}
              </span>
            )}
          </>
        )}
          </div>

          {/* Engagement bar — 44px touch targets, select-none so taps register as buttons */}
          <div className="flex items-center gap-1 px-3 py-2 lg:gap-4 lg:px-4 lg:py-2.5 border-t border-gray-100 text-gray-600 select-none">
        <button
          type="button"
          onClick={() => onLike(post.id)}
          className={`flex items-center gap-1.5 text-xs font-medium lg:text-sm min-w-[44px] min-h-[44px] justify-center rounded-xl active:bg-gray-100 ${liked.has(post.id) ? "text-red-500" : "hover:text-[#008080]"}`}
        >
          <Heart className={`w-4 h-4 lg:w-5 lg:h-5 ${liked.has(post.id) ? "fill-red-500" : ""}`} strokeWidth={2} />
          {post.likes + (liked.has(post.id) ? 1 : 0)}
        </button>
        <span className="flex items-center gap-1.5 text-xs font-medium lg:text-sm min-w-[44px] min-h-[44px] justify-center">
          <CommentIcon className="w-4 h-4 lg:w-5 lg:h-5 text-[#008080]" strokeWidth={2} />
          {post.comments}
        </span>
        <span className="flex items-center gap-1.5 text-xs font-medium lg:text-sm min-w-[44px] min-h-[44px] justify-center text-[#008080]">
          <Share2 className="w-4 h-4 lg:w-5 lg:h-5" strokeWidth={2} />
          <Coins className="w-3 h-3 lg:w-4 lg:h-4" strokeWidth={2} />
          {isHe ? "שתף" : "Share"}
        </span>
        <button
          type="button"
          onClick={(e) => { e.stopPropagation(); handleCopy(); }}
          className={`flex items-center gap-1.5 min-w-[44px] min-h-[44px] justify-center rounded-xl active:bg-gray-100 transition-colors ${justCopied ? "text-[#008080]" : "text-gray-500 hover:text-[#008080]"}`}
          aria-label={isHe ? "העתק" : "Copy"}
          title={isHe ? "העתק כותרת ותקציר" : "Copy title and summary"}
        >
          <Clipboard className="w-4 h-4 lg:w-5 lg:h-5 shrink-0" strokeWidth={2} />
          {justCopied && <span className="text-xs font-semibold text-[#008080] whitespace-nowrap">{isHe ? "הועתק!" : "Copied!"}</span>}
        </button>
        <span className="flex items-center gap-1.5 text-xs font-medium lg:text-sm min-w-[44px] min-h-[44px] justify-center ml-auto">
          <Eye className="w-4 h-4 lg:w-5 lg:h-5 text-gray-400" strokeWidth={2} />
          {post.views}
        </span>
          </div>

          {/* Comments with expandable replies */}
      {post.commentsList.length > 0 && (
        <div className="px-4 pb-4 pt-1 border-t border-gray-50">
          <p className="text-xs font-semibold text-gray-500 uppercase tracking-wide mb-2">{isHe ? "תגובות" : "Comments"}</p>
          {post.commentsList.map((comment) => (
            <div key={comment.id} className="mb-2">
              <div className="flex gap-2">
                <div className="w-7 h-7 rounded-full bg-gray-200 flex items-center justify-center text-[10px] font-medium text-gray-600 shrink-0">
                  {getInitial(comment.authorName)}
                </div>
                <div className="flex-1 min-w-0">
                  <p className="text-xs font-medium text-gray-900">{comment.authorName}</p>
                  <p className="text-sm text-gray-700">{comment.text}</p>
                  <p className="text-[10px] text-gray-400 mt-0.5">{formatRelative(comment.timestamp)}</p>
                  {comment.replies && comment.replies.length > 0 && (
                    <button
                      type="button"
                      onClick={() => toggleReplies(comment.id)}
                      className="mt-1.5 flex items-center gap-1 text-xs font-medium text-[#008080] hover:underline"
                    >
                      {showReplies[comment.id] ? (
                        <>
                          <ChevronUp className="w-3.5 h-3.5" strokeWidth={2} />
                          {isHe ? "הסתר תגובות" : "Hide replies"}
                        </>
                      ) : (
                        <>
                          <ChevronDown className="w-3.5 h-3.5" strokeWidth={2} />
                          {isHe ? `הצג ${comment.replies.length} תגובות` : `View ${comment.replies.length} replies`}
                        </>
                      )}
                    </button>
                  )}
                  {showReplies[comment.id] && comment.replies && (
                    <div className="mt-2 ml-2 pl-3 border-l-2 border-gray-100 space-y-2">
                      {comment.replies.map((r) => (
                        <div key={r.id}>
                          <p className="text-xs font-medium text-gray-900">{r.authorName}</p>
                          <p className="text-sm text-gray-700">{r.text}</p>
                          <p className="text-[10px] text-gray-400">{formatRelative(r.timestamp)}</p>
                        </div>
                      ))}
                    </div>
                  )}
                </div>
              </div>
            </div>
          ))}
          </div>
      )}

          {/* Action buttons: viral loop — Credit Reward icon on Share/Apply; Source Link for jobs; Contact via Ollin for pros */}
      {post.category === "deals" && (
        <div className="px-4 pb-4 flex flex-col gap-2">
          <button type="button" className="w-full py-2.5 rounded-xl text-white text-sm font-medium bg-[#008080] hover:bg-[#006666] flex items-center justify-center gap-2">
            <Coins className="w-4 h-4" strokeWidth={2} />
            {post.generatedByAI ? (isHe ? "צפה במבצע — הרווח קרדיטים" : "View Deal — Earn Credits") : (isHe ? "פרטים" : "Details")}
          </button>
          <button type="button" className="w-full py-2 rounded-xl border border-[#008080]/40 text-[#008080] text-sm font-medium hover:bg-[#008080]/5 flex items-center justify-center gap-2">
            <Share2 className="w-4 h-4" strokeWidth={2} />
            <Coins className="w-3.5 h-3.5" strokeWidth={2} />
            {isHe ? "שתף וקבל קרדיטים" : "Share for Credits"}
          </button>
        </div>
      )}
      {post.category === "gossip" && (
        <div className="px-4 pb-4">
          <button type="button" className="w-full py-2.5 rounded-xl text-white text-sm font-medium bg-[#008080] hover:bg-[#006666] flex items-center justify-center gap-2">
            <Share2 className="w-4 h-4" strokeWidth={2} />
            <Coins className="w-4 h-4" strokeWidth={2} />
            {isHe ? "שתף וקבל קרדיטים" : "Share for Credits"}
          </button>
        </div>
      )}
      {post.category === "jobs" && (
        <div className="px-3 pb-3 space-y-2">
          {post.sourceLink && post.sourceName && (
            <a
              href={post.sourceLink}
              target="_blank"
              rel="noopener noreferrer"
              onClick={handleSourceClick}
              className="flex items-center justify-center gap-2 w-full py-2 rounded-xl border border-gray-200 text-gray-700 text-sm font-medium hover:bg-gray-50"
            >
              <ExternalLink className="w-4 h-4" strokeWidth={2} />
              {isHe ? "מקור" : "Source"}: {post.sourceName}
            </a>
          )}
          <button type="button" onClick={() => onApplyClick?.(post)} className="w-full py-2.5 rounded-xl text-white text-sm font-medium bg-[#008080] hover:bg-[#006666] flex flex-col items-center gap-1">
            <span className="flex items-center gap-2">
              <Coins className="w-4 h-4" strokeWidth={2} />
              Ollin Quick Apply
            </span>
            <span className="text-[10px] opacity-90 font-medium">{isHe ? "נשלח דרך Ollin" : "Sent via Ollin"}</span>
          </button>
        </div>
      )}
      {post.category === "pros" && (
        <div className="px-4 pb-4">
          <p className="text-[10px] text-gray-500 mb-1.5 px-0.5">{isHe ? "הודעה/שיחה תתחיל ב: \"הי, מצאתי אותך דרך Ollin...\"" : "Message/call will start with: \"Hi, I found you through Ollin...\""}</p>
          <button type="button" className="w-full py-2.5 rounded-xl text-white text-sm font-medium bg-[#008080] hover:bg-[#006666] flex items-center justify-center gap-2">
            <Phone className="w-4 h-4" strokeWidth={2} />
            {isHe ? "צור קשר דרך Ollin" : "Contact via Ollin"}
          </button>
        </div>
      )}

          {/* View Original / Source link — every AI post; clearly marked as leaving the app */}
          {post.generatedByAI && sourceHref && (
            <div className="px-3 pb-3 pt-0 border-t border-gray-50">
              <p className="text-[10px] text-gray-500 font-medium mb-1">{post.sourceLabel}</p>
              <a
                href={sourceHref}
                target="_blank"
                rel="noopener noreferrer"
                onClick={post.category === "deals" ? handleSourceClick : post.category === "jobs" ? handleSourceClick : undefined}
                className="inline-flex items-center gap-1.5 text-xs font-medium text-[#008080] hover:underline"
              >
                <ExternalLink className="w-3.5 h-3.5" strokeWidth={2} />
                {isHe ? "צפה במקור" : "View Original"}
                {sourceDisplayName && sourceDisplayName !== "Original" && ` (${sourceDisplayName})`}
              </a>
              <p className="text-[10px] text-gray-400 mt-0.5">{isHe ? "תע покинуть את האפליקציה" : "You're leaving the app to the original source."}</p>
            </div>
          )}
        </div>
      </div>
    </article>
  );
}

export function ExplorePanel() {
  const { locale } = useLocale();
  const [tab, setTab] = useState<ExploreTab>("all");
  const [location, setLocation] = useState("");
  const [radiusKm, setRadiusKm] = useState(5);
  const [locationPillOpen, setLocationPillOpen] = useState(false);
  const [mapOpen, setMapOpen] = useState(false);
  const [prosSearch, setProsSearch] = useState("");
  const [jobsSearch, setJobsSearch] = useState("");
  const [showTenderForm, setShowTenderForm] = useState(false);
  const [tenderTitle, setTenderTitle] = useState("");
  const [tenderDescription, setTenderDescription] = useState("");
  const [loading, setLoading] = useState(true);
  const [liked, setLiked] = useState<Set<string>>(new Set());
  const [insightPosts, setInsightPosts] = useState<ExplorePost[]>([]);
  const insightIndexRef = React.useRef(0);
  const [searchQuery, setSearchQuery] = useState("");
  const [creditsToast, setCreditsToast] = useState(false);
  const [directionsTarget, setDirectionsTarget] = useState<{ address: string; title?: string } | null>(null);
  const [userCoords, setUserCoords] = useState<{ lat: number; lng: number } | null>(HAIFA_CENTER);
  const [liveSignalPosts, setLiveSignalPosts] = useState<ExplorePost[]>([]);
  const [liveSignalsSource, setLiveSignalsSource] = useState<string>("");
  const [lastAiQuery, setLastAiQuery] = useState<string>("");
  const [devModeOpen, setDevModeOpen] = useState(false);
  const [refineToast, setRefineToast] = useState(false);
  const interactionLogRef = React.useRef({ jobCardsViewed: 0, applyClicks: 0, directionsClicks: 0, dealCardsViewed: 0, sourceClicks: 0 });

  useEffect(() => {
    const t = setTimeout(() => setLoading(false), 600);
    return () => clearTimeout(t);
  }, []);

  // Force geolocation on mount; fallback to Haifa center if GPS unavailable so distances always show
  useEffect(() => {
    getCurrentPosition().then((coords) => {
      if (coords) setUserCoords(coords);
    });
  }, []);

  // Live data: search for real local news, rumors, deals in current city
  useEffect(() => {
    const city = location.trim() || "Haifa";
    analyzeLocalSignals(city).then(({ posts, source, query }) => {
      setLiveSignalPosts(posts);
      setLiveSignalsSource(source);
      setLastAiQuery(query);
    });
  }, [location.trim() || "Haifa"]);

  // Every 30s, prepend one new "AI Insight" post to simulate real-time ingestion
  useEffect(() => {
    const interval = setInterval(() => {
      const template = INSIGHT_TEMPLATES[insightIndexRef.current % INSIGHT_TEMPLATES.length];
      insightIndexRef.current += 1;
      const newPost: ExplorePost = {
        ...template,
        id: `insight-${Date.now()}-${Math.random().toString(36).slice(2, 8)}`,
        timestamp: "Just now",
        commentsList: [],
      };
      setInsightPosts((prev) => [newPost, ...prev].slice(0, 20));
    }, 30000);
    return () => clearInterval(interval);
  }, []);

  // Dev Mode: Ctrl+Shift+D / Cmd+Shift+D
  useEffect(() => {
    const onKey = (e: KeyboardEvent) => {
      if ((e.ctrlKey || e.metaKey) && e.shiftKey && e.key === "D") {
        e.preventDefault();
        setDevModeOpen((o) => !o);
      }
    };
    window.addEventListener("keydown", onKey);
    return () => window.removeEventListener("keydown", onKey);
  }, []);

  const isHe = locale === "he";
  const cityName = location.trim() || "Haifa";
  const { state: architectState, setExploreSortByDistance, setExploreContextForArchitect } = useArchitect();

  const tabs: { id: ExploreTab; labelEn: string; labelHe: string }[] = [
    { id: "all", labelEn: "ALL", labelHe: "הכל" },
    { id: "deals", labelEn: "Deals", labelHe: "מבצעים" },
    { id: "gossip", labelEn: "Gossip", labelHe: "רכילות" },
    { id: "jobs", labelEn: "Jobs", labelHe: "משרות" },
    { id: "pros", labelEn: "Pros", labelHe: "מקצוענים" },
  ];

  // Filter sample posts by tab and location
  const filteredPosts = useMemo(() => {
    let list: ExplorePost[] = SAMPLE_POSTS;
    if (tab !== "all") list = list.filter((p) => p.category === tab);
    if (location.trim()) {
      const locLower = location.trim().toLowerCase();
      list = list.filter((p) => p.location?.toLowerCase().includes(locLower));
    }
    return list;
  }, [tab, location]);

  // Merge insights + live signals + samples; filter by tab & search; apply real distance from userCoords
  const displayPosts = useMemo(() => {
    const insights = insightPosts.filter((p) => tab === "all" || p.category === tab);
    const live = liveSignalPosts.filter((p) => tab === "all" || p.category === tab);
    const merged = [...insights, ...live, ...filteredPosts];
    let list = merged;
    if (searchQuery.trim()) {
      const q = searchQuery.trim().toLowerCase();
      list = list.filter(
        (p) =>
          p.title.toLowerCase().includes(q) ||
          p.description.toLowerCase().includes(q) ||
          p.authorName.toLowerCase().includes(q) ||
          p.location?.toLowerCase().includes(q) ||
          p.specialty?.toLowerCase().includes(q)
      );
    }
    const coords = userCoords;
    let result = list.map((p) => {
      const distanceMeters =
        coords && p.lat != null && p.lng != null
          ? haversineMeters(coords.lat, coords.lng, p.lat, p.lng)
          : p.distanceMeters;
      return { ...p, distanceMeters };
    });
    return result;
  }, [insightPosts, liveSignalPosts, filteredPosts, tab, searchQuery, userCoords]);

  const displayPostsSorted = useMemo(() => {
    if (!architectState.exploreSortByDistance) return displayPosts;
    return [...displayPosts].sort((a, b) => {
      const da = a.distanceMeters ?? Infinity;
      const db = b.distanceMeters ?? Infinity;
      return da - db;
    });
  }, [displayPosts, architectState.exploreSortByDistance]);

  // Global State Bridge: when Architect has bridge enabled, push Explore context so it can offer relevant AI prompts
  useEffect(() => {
    if (!architectState.exploreBridgeEnabled) return;
    setExploreContextForArchitect({
      lastCategory: tab,
      lastQuery: searchQuery.trim() || undefined,
      recentItemIds: displayPosts.slice(0, 20).map((p) => p.id),
      updatedAt: Date.now(),
    });
  }, [architectState.exploreBridgeEnabled, tab, searchQuery, displayPosts, setExploreContextForArchitect]);

  // Interaction log for Dev Mode: track views vs clicks
  useEffect(() => {
    const jobs = displayPosts.filter((p) => p.category === "jobs");
    const deals = displayPosts.filter((p) => p.category === "deals");
    interactionLogRef.current.jobCardsViewed = Math.max(interactionLogRef.current.jobCardsViewed, jobs.length);
    interactionLogRef.current.dealCardsViewed = Math.max(interactionLogRef.current.dealCardsViewed, deals.length);
  }, [displayPosts]);

  const handleLike = (postId: string) => {
    setLiked((prev) => {
      const next = new Set(prev);
      if (next.has(postId)) next.delete(postId);
      else next.add(postId);
      return next;
    });
  };

  const handleSourceClick = useCallback(() => {
    interactionLogRef.current.sourceClicks += 1;
    setCreditsToast(true);
    setTimeout(() => setCreditsToast(false), 4000);
  }, []);

  const handleGetDirections = useCallback((address: string, title?: string) => {
    interactionLogRef.current.directionsClicks += 1;
    setDirectionsTarget(address ? { address, title } : null);
  }, []);

  const handleApplyClick = useCallback(() => {
    interactionLogRef.current.applyClicks += 1;
  }, []);

  const handleRefineView = useCallback(() => {
    const state = {
      tab,
      location: cityName,
      radiusKm,
      searchQuery,
      visiblePostIds: displayPosts.slice(0, 15).map((p) => p.id),
      timestamp: new Date().toISOString(),
    };
    navigator.clipboard.writeText(JSON.stringify(state, null, 2));
    setRefineToast(true);
    setTimeout(() => setRefineToast(false), 3000);
  }, [tab, cityName, radiusKm, searchQuery, displayPosts]);

  const mapCenter = userCoords ?? HAIFA_CENTER;
  const mapBbox = `${mapCenter.lng - 0.05},${mapCenter.lat - 0.04},${mapCenter.lng + 0.05},${mapCenter.lat + 0.04}`;
  const osmEmbedUrl = `https://www.openstreetmap.org/export/embed.html?bbox=${mapBbox}&layer=mapnik&marker=${mapCenter.lat},${mapCenter.lng}`;

  return (
    <div className="flex flex-col lg:flex-row flex-1 min-h-0 overflow-hidden border border-gray-200 bg-white relative">
      {/* Directions modal: From My Location → To address; Open in Maps */}
      {directionsTarget && (
        <DirectionsModal
          destinationAddress={directionsTarget.address}
          destinationTitle={directionsTarget.title}
          onClose={() => setDirectionsTarget(null)}
          isHe={isHe}
        />
      )}

      {/* Developer Mode: interaction gaps + AI logic (Ctrl+Shift+D / Cmd+Shift+D) */}
      {devModeOpen && (
        <>
          <div className="fixed inset-0 z-50 bg-black/40" onClick={() => setDevModeOpen(false)} aria-hidden />
          <div className="fixed right-0 top-0 bottom-0 z-50 w-full max-w-sm bg-white border-l border-gray-200 shadow-xl overflow-y-auto p-4" onClick={(e) => e.stopPropagation()}>
            <div className="flex items-center justify-between mb-4">
              <h3 className="font-bold text-gray-900 flex items-center gap-2">
                <Code className="w-5 h-5 text-[#008080]" strokeWidth={2} />
                {isHe ? "מצב מפתח" : "Developer Mode"}
              </h3>
              <button type="button" onClick={() => setDevModeOpen(false)} className="p-2 rounded-lg hover:bg-gray-100 text-gray-600">×</button>
            </div>
            <section className="mb-4">
              <p className="text-xs font-semibold text-gray-500 uppercase mb-2">{isHe ? "לוגיקת AI" : "AI logic"}</p>
              <p className="text-xs text-gray-700 break-words"><span className="font-medium">{isHe ? "שאילתה אחרונה:" : "Last query:"}</span> {lastAiQuery || "—"}</p>
              <p className="text-xs text-gray-700 mt-1"><span className="font-medium">{isHe ? "מקור:" : "Source:"}</span> {liveSignalsSource || "—"}</p>
              <p className="text-xs text-gray-500 mt-1">{isHe ? "מיקום משתמש:" : "User location:"} {userCoords ? `${userCoords.lat.toFixed(4)}, ${userCoords.lng.toFixed(4)}` : "—"}</p>
            </section>
            <section className="mb-4">
              <p className="text-xs font-semibold text-gray-500 uppercase mb-2">{isHe ? "פערים באינטראקציה" : "Interaction gaps"}</p>
              <ul className="text-xs text-gray-700 space-y-1">
                <li>Job cards shown: {interactionLogRef.current.jobCardsViewed} → Apply clicks: {interactionLogRef.current.applyClicks}</li>
                <li>Deal cards shown: {interactionLogRef.current.dealCardsViewed} → Source clicks: {interactionLogRef.current.sourceClicks}</li>
                <li>Get Directions clicks: {interactionLogRef.current.directionsClicks}</li>
              </ul>
            </section>
            <section>
              <p className="text-xs font-semibold text-gray-500 uppercase mb-2">{isHe ? "הצעות לפיצ'רים" : "Suggested features"}</p>
              <ul className="text-xs text-gray-600 space-y-1">
                {interactionLogRef.current.jobCardsViewed > 0 && interactionLogRef.current.applyClicks === 0 && (
                  <li>• One-tap Apply from card (reduce friction)</li>
                )}
                {interactionLogRef.current.directionsClicks === 0 && displayPosts.some((p) => p.address) && (
                  <li>• Promote Get Directions on first visit</li>
                )}
                <li>• Geocode addresses for live signals to show exact distance</li>
                <li>• Add TAVILY_API_KEY or SERPER_API_KEY for richer live results</li>
              </ul>
            </section>
          </div>
        </>
      )}

      {/* Toast: Keep Ollin open to claim credits after purchase (when user clicks Source on Deal/Job) */}
      {creditsToast && (
        <div className="fixed bottom-20 left-4 right-4 z-50 flex justify-center pointer-events-none">
          <div className="px-4 py-3 rounded-xl bg-[#008080] text-white text-sm font-medium shadow-lg flex items-center gap-2 animate-in fade-in duration-200">
            <Coins className="w-4 h-4 shrink-0" strokeWidth={2} />
            {isHe ? "השאר את Ollin פתוח כדי לקבל קרדיטים אחרי הרכישה!" : "Keep Ollin open to claim your credits after purchase!"}
          </div>
        </div>
      )}

      {/* Desktop: fixed left sidebar — Navigation Tabs (Deals, Gossip, Jobs, Pros) */}
      <aside className="hidden lg:flex lg:flex-col lg:w-52 lg:shrink-0 border-r border-gray-200 bg-gray-50/50 py-4">
        <div className="px-3 mb-2">
          <h2 className="text-sm font-bold text-gray-500 uppercase tracking-wide">{isHe ? "גילוי" : "Explore"}</h2>
        </div>
        <nav className="flex flex-col gap-0.5 px-2">
          {tabs.map(({ id, labelEn, labelHe }) => (
            <button
              key={id}
              type="button"
              onClick={() => setTab(id)}
              className={`text-left px-3 py-2.5 rounded-xl text-sm font-medium transition-colors ${tab === id ? "bg-[#008080] text-white" : "text-gray-600 hover:bg-gray-200"}`}
            >
              {isHe ? labelHe : labelEn}
            </button>
          ))}
        </nav>
      </aside>

      {/* Main: header + tabs + feed via shared PanelWrapper */}
      <div className="flex-1 flex flex-col min-w-0">
      {/* Location popover: only when clicking "Set location" */}
      {locationPillOpen && (
        <>
          <div className="fixed inset-0 z-40" onClick={() => setLocationPillOpen(false)} aria-hidden />
          <div className="absolute right-3 top-14 z-50 w-64 rounded-xl bg-white border border-gray-200 shadow-xl p-4">
            <p className="text-xs font-semibold text-gray-700 mb-2">{isHe ? "מיקום" : "Location"}</p>
            <p className="px-0.5 py-1 text-[10px] font-semibold text-gray-500 uppercase">{isHe ? "רדיוס (ק״מ)" : "Radius (km)"}</p>
            <div className="flex flex-wrap gap-1.5 mb-3">
              {RADII_OPTIONS.map((km) => (
                <button
                  key={km}
                  type="button"
                  onClick={() => setRadiusKm(km)}
                  className={`px-2.5 py-1.5 rounded-xl text-xs font-medium ${radiusKm === km ? "bg-[#008080] text-white" : "bg-gray-100 text-gray-700 hover:bg-gray-200"}`}
                >
                  {km} km
                </button>
              ))}
            </div>
            <p className="px-0.5 py-1 text-[10px] font-semibold text-gray-500 uppercase mt-1">{isHe ? "עיר או כתובת" : "City or address"}</p>
            <div className="flex gap-2 mt-1">
              <MapPin className="w-4 h-4 text-[#008080] shrink-0 mt-2.5" strokeWidth={2} />
              <input
                type="text"
                value={location}
                onChange={(e) => setLocation(e.target.value)}
                placeholder={isHe ? "הזן עיר או כתובת" : "Enter city or address"}
                className="flex-1 min-w-0 rounded-xl border border-gray-200 px-2.5 py-2 text-sm"
              />
            </div>
            <button type="button" onClick={() => setLocationPillOpen(false)} className="mt-4 w-full py-2.5 rounded-xl bg-[#008080] text-white text-sm font-medium hover:bg-[#006666]">
              {isHe ? "סיום" : "Done"}
            </button>
          </div>
        </>
      )}

        <PanelWrapper
          header={
            <>
              <header className="px-3 py-2.5 lg:px-6 border-b border-gray-200 flex flex-wrap items-center gap-2">
                <Compass className="w-5 h-5 text-[#008080] shrink-0" strokeWidth={2} />
                <h2 className="text-lg font-semibold text-gray-900 shrink-0 lg:hidden">{isHe ? "גילוי" : "Explore"}</h2>
                <button type="button" onClick={() => setDevModeOpen((o) => !o)} className="p-1.5 rounded-xl hover:bg-gray-100 text-gray-400 hover:text-[#008080]" title={isHe ? "מצב מפתח (Ctrl+Shift+D)" : "Developer mode (Ctrl+Shift+D)"} aria-label="Dev mode">
                  <Code className="w-4 h-4" strokeWidth={2} />
                </button>
                <div className="flex-1 min-w-0 min-w-[200px] flex items-center gap-2 rounded-xl border border-gray-200 bg-gray-50/50 pl-2.5 pr-2 py-1.5 lg:max-w-xl">
                  <Search className="w-4 h-4 text-gray-400 shrink-0" strokeWidth={2} />
                  <input
                    type="text"
                    value={searchQuery}
                    onChange={(e) => setSearchQuery(e.target.value)}
                    placeholder={isHe ? "חיפוש מבצעים, משרות, מקצוענים..." : "Search deals, jobs, pros..."}
                    className="flex-1 min-w-0 py-1.5 text-sm text-gray-900 placeholder-gray-400 outline-none bg-transparent"
                  />
                </div>
                <button
                  type="button"
                  onClick={() => setLocationPillOpen((o) => !o)}
                  className={`flex-shrink-0 inline-flex items-center gap-1.5 px-3 py-2 rounded-full text-sm font-medium transition-colors border ${locationPillOpen ? "bg-[#008080] text-white border-[#008080]" : "bg-gray-50/90 border-gray-200 text-gray-700 hover:bg-gray-100"}`}
                  title={isHe ? "הגדר מיקום ורדיוס" : "Set location and radius"}
                  aria-label={isHe ? "הגדר מיקום" : "Set location"}
                >
                  <MapPin className="w-4 h-4 shrink-0" strokeWidth={2} />
                  <span>{isHe ? "הגדר מיקום" : "Set location"}</span>
                </button>
              </header>
              <div className="lg:hidden flex items-center gap-2 border-b border-gray-200 p-2 overflow-hidden">
                <div className="flex overflow-x-auto gap-0.5 min-w-0 flex-1 scrollbar-hide">
                  {tabs.map(({ id, labelEn, labelHe }) => (
                    <button
                      key={id}
                      type="button"
                      onClick={() => setTab(id)}
                      className={`flex-shrink-0 px-4 py-2.5 rounded-xl text-sm font-medium whitespace-nowrap transition-colors ${tab === id ? "bg-[#008080] text-white" : "text-gray-600 hover:bg-gray-100"}`}
                    >
                      {isHe ? labelHe : labelEn}
                    </button>
                  ))}
                </div>
              </div>
            </>
          }
          className="min-w-0"
        >
            <div className="flex justify-center p-4 lg:px-6">
            <div className="w-full max-w-[700px]">
        {loading ? (
          <SkeletonFeed count={3} />
        ) : (
          <>
            {tab === "pros" && (
              <>
                <p className="text-xs text-gray-500 mb-2">{isHe ? "חיפוש מקצוענים עם מסננים" : "Search pros with filters"}</p>
                <div className="flex gap-2 mb-3">
                  <input
                    type="text"
                    value={prosSearch}
                    onChange={(e) => setProsSearch(e.target.value)}
                    placeholder={isHe ? "תחום או מקצוע" : "Category or trade"}
                    className="flex-1 rounded-xl border border-gray-200 px-3 py-2 text-sm"
                  />
                  <button type="button" className="p-2 rounded-xl bg-[#008080] text-white">
                    <Search className="w-5 h-5" strokeWidth={2} />
                  </button>
                </div>
              </>
            )}

            {tab === "jobs" && (
              <>
                <p className="text-xs text-gray-500 mb-2">{isHe ? "חיפוש משרות עם מסננים" : "Search jobs with filters"}</p>
                <div className="flex gap-2 mb-3">
                  <input
                    type="text"
                    value={jobsSearch}
                    onChange={(e) => setJobsSearch(e.target.value)}
                    placeholder={isHe ? "תפקיד או חברה" : "Role or company"}
                    className="flex-1 rounded-xl border border-gray-200 px-3 py-2 text-sm"
                  />
                  <button type="button" className="p-2 rounded-xl bg-[#008080] text-white">
                    <Search className="w-5 h-5" strokeWidth={2} />
                  </button>
                </div>
                <button
                  type="button"
                  onClick={() => setShowTenderForm((o) => !o)}
                  className="w-full flex items-center justify-center gap-2 py-4 rounded-xl border-2 border-dashed border-[#008080]/40 text-[#008080] font-medium text-sm hover:bg-[#008080]/5 mb-4"
                >
                  <Plus className="w-5 h-5" strokeWidth={2} />
                  {isHe ? "פרסום מכרז אישי (משרה למקצוענים)" : "Post Personal Tender"}
                </button>
                {showTenderForm && (
                  <div className="rounded-xl border border-gray-200 p-6 space-y-3 mb-4">
                    <input
                      type="text"
                      value={tenderTitle}
                      onChange={(e) => setTenderTitle(e.target.value)}
                      placeholder={isHe ? "כותרת המכרז" : "Tender title"}
                      className="w-full rounded-xl border border-gray-200 px-3 py-2 text-sm"
                    />
                    <textarea
                      value={tenderDescription}
                      onChange={(e) => setTenderDescription(e.target.value)}
                      placeholder={isHe ? "תיאור — מקצוענים יוכלו להגיש הצעות" : "Description — pros can submit bids"}
                      rows={3}
                      className="w-full rounded-xl border border-gray-200 px-3 py-2 text-sm resize-none"
                    />
                    <div className="flex gap-2">
                      <button type="button" onClick={() => setShowTenderForm(false)} className="flex-1 py-2.5 rounded-xl border border-gray-300 text-sm">{isHe ? "ביטול" : "Cancel"}</button>
                      <button type="button" className="flex-1 py-2.5 rounded-xl bg-[#008080] text-white text-sm">{isHe ? "פרסם מכרז" : "Post Tender"}</button>
                    </div>
                  </div>
                )}
              </>
            )}

            {/* Scan Area: Ollin is scanning local signals — pulse/radar + real-time ingestion */}
            <div className="explore-scan-radar flex items-center gap-2 px-3 py-2.5 rounded-xl bg-[#008080]/5 border border-[#008080]/20 mb-2">
              <span className="relative flex h-8 w-8 shrink-0 items-center justify-center">
                <span className="absolute inline-flex h-6 w-6 rounded-full bg-[#008080]/30 animate-ping opacity-60" />
                <ScanLine className="relative h-4 w-4 text-[#008080]" strokeWidth={2} />
              </span>
              <div className="flex-1 min-w-0">
                <p className="text-xs font-semibold text-[#008080]">{isHe ? "אולין סורקת אותות מקומיים..." : "Ollin is scanning local signals..."}</p>
                <p className="text-[10px] text-gray-500">{liveSignalsSource ? `${isHe ? "מקור" : "Source"}: ${liveSignalsSource}` : (isHe ? "מעדכן תוכן בזמן אמת" : "Real-time data ingestion")}</p>
              </div>
              <span className="flex gap-0.5">
                <span className="w-1.5 h-1.5 rounded-full bg-[#008080] animate-pulse" style={{ animationDelay: "0ms" }} />
                <span className="w-1.5 h-1.5 rounded-full bg-[#008080] animate-pulse" style={{ animationDelay: "200ms" }} />
                <span className="w-1.5 h-1.5 rounded-full bg-[#008080] animate-pulse" style={{ animationDelay: "400ms" }} />
              </span>
            </div>
            {/* Refine this view: capture UI state for AI iteration */}
            <button
              type="button"
              onClick={handleRefineView}
              className="w-full flex items-center justify-center gap-2 py-2.5 rounded-xl border border-[#008080]/30 text-[#008080] text-sm font-medium hover:bg-[#008080]/5 mb-4"
            >
              <Sparkles className="w-4 h-4" strokeWidth={2} />
              {isHe ? "שפר את התצוגה (העתק למה״ל)" : "Refine this view (copy state)"}
            </button>
            {refineToast && (
              <p className="text-xs text-[#008080] font-medium mb-2 text-center">{isHe ? "מצב הועתק ללוח — מוכן לאיטרציה של AI" : "State copied to clipboard — ready for AI iteration"}</p>
            )}

            {/* Social feed: single centered column (Facebook/LinkedIn style) */}
            <div className="space-y-5 lg:space-y-6">
              {architectState.exploreSortByDistance && (
                <div className="flex items-center gap-2 mb-3 px-1">
                  <span className="inline-flex items-center gap-1.5 px-3 py-1.5 rounded-full bg-[#008080]/15 text-[#008080] text-xs font-semibold">
                    {isHe ? "קרוב אליי קודם" : "Near me first"}
                  </span>
                  <button type="button" onClick={() => setExploreSortByDistance(false)} className="text-xs text-gray-500 hover:text-gray-700 underline">
                    {isHe ? "בטל" : "Turn off"}
                  </button>
                </div>
              )}
              {displayPostsSorted.length === 0 ? (
                <div className="rounded-xl border border-gray-200 p-8 text-center text-sm text-gray-500">
                  {location.trim()
                    ? (isHe ? "אין פוסטים התואמים את המיקום שנבחר." : "No posts match the selected location.")
                    : (isHe ? "אין פוסטים להצגה." : "No posts to show.")}
                </div>
              ) : (
                displayPostsSorted.map((post) => (
                  <PostCard key={post.id} post={post} isHe={isHe} onLike={handleLike} liked={liked} onSourceClick={handleSourceClick} onGetDirections={handleGetDirections} onApplyClick={handleApplyClick} />
                ))
              )}
            </div>
          </>
        )}
            </div>
            </div>
        </PanelWrapper>

          {/* Floating map FAB — collapsible map */}
          <button
            type="button"
            onClick={() => setMapOpen((o) => !o)}
            className="fixed bottom-20 right-4 z-30 w-12 h-12 rounded-full bg-[#008080] text-white shadow-lg hover:bg-[#006666] flex items-center justify-center lg:w-14 lg:h-14 lg:bottom-6 lg:right-6"
            aria-label={isHe ? "הצג מפה" : "Show map"}
          >
            <MapPin className="w-5 h-5 lg:w-6 lg:h-6" strokeWidth={2} />
          </button>

          {/* Collapsible map drawer (right sidebar) */}
          {mapOpen && (
            <>
              <div className="fixed inset-0 z-40 bg-black/30" onClick={() => setMapOpen(false)} aria-hidden />
              <div className="fixed top-0 right-0 bottom-0 z-50 w-full max-w-md bg-white border-l border-gray-200 shadow-xl flex flex-col">
                <div className="flex-shrink-0 px-4 py-3 border-b border-gray-200 flex items-center justify-between">
                  <span className="text-sm font-semibold text-gray-900 flex items-center gap-2">
                    <MapPin className="w-4 h-4 text-[#008080]" strokeWidth={2} />
                    {isHe ? "מפה" : "Map"}
                  </span>
                  <button type="button" onClick={() => setMapOpen(false)} className="p-2 rounded-lg hover:bg-gray-100 text-gray-600">×</button>
                </div>
                <div className="flex-1 min-h-0 relative">
                  <iframe
                    title={isHe ? "מפת אזור" : "Area map"}
                    src={osmEmbedUrl}
                    className="absolute inset-0 w-full h-full border-0"
                    loading="lazy"
                    referrerPolicy="no-referrer"
                  />
                </div>
                <div className="flex-shrink-0 px-3 py-2 border-t border-gray-200 text-[10px] text-gray-500">
                  {isHe ? "מיקום משוער — מרכז לפי המיקום שלך או חיפה" : "Approximate location — centered on your position or Haifa"}
                </div>
              </div>
            </>
          )}
      </div>
    </div>
  );
}
